#必须utf-8格式保存

spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: micservice-config-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: micservice-config--test