#必须utf-8格式保存

spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201
spring:
  profiles: dev
  application: 
    name: micservice-config-client
eureka: 
  client: 
      defaultZone: http://eureka7001.com:7001/eureka
    service-url: 
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: micservice-config-client2222
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka