#必须utf-8格式保存

spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201
  xxx: nnnn
spring:
  profiles: dev
  application: 
    name: micservice-config-client
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
     
---
server: 
  port: 8202 
  xxx: zzzzzsdfasdfasdfas
spring:
  profiles: test
  application: 
    name: micservice-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka